### ISSUE TITLE
The alert modal will also shown when metadata is not initialized.

### ISSUE THREAD

**Issue by HuberTRoy** [subquery/indexer-admin#87]
Reproduce Steps:

1. Have an indexing project that status is READY.
2. On Project page click that project.
3. Will show a empty alert.

Problem code snippets:

```ts
  const projectStatus = useMemo(() => {
    const healthy = metadata?.indexerStatus === 'HEALTHY';
    switch (status) {
      case IndexingStatus.NOTINDEXING:
        return healthy ? ProjectStatus.Started : ProjectStatus.NotIndexing;
      case IndexingStatus.INDEXING:
        return healthy ? ProjectStatus.Indexing : ProjectStatus.Terminated;
      case IndexingStatus.READY:
        return healthy ? ProjectStatus.Ready : ProjectStatus.Terminated;
      default:
        return ProjectStatus.NotIndexing;
    }
  }, [status, metadata]);

  const alertInfo = useMemo(
    () =>
      projectStatus === ProjectStatus.Terminated
        ? { visible: true, ...alertMessages[projectStatus] }
        : { visible: false },
    [projectStatus]
  );
...
 <AlertView {...alertInfo} />
```

When `metadata` is `undefined` and project is INDEXING the switch condition will match  `return healthy ? ProjectStatus.Indexing : ProjectStatus.Terminated` and return `Terminated` then `alertInfo` will return `{ visible: true }`.

`AlertView ` did not effect the props change, so will show the alert and no message in.

Solve:
1. when metadata is `undefined`, return the default status `NotIndexing`.
2. AlertView effect the props change.

**Comment by ianhe8x** [comment]
Duplicated with https://onfinality.atlassian.net/browse/SQN-1458 but good to have some more details.

**Comment by HuberTRoy** [comment]
@ianhe8x 

Assign this to me?  I will fix it.
